language: objective-c
osx_image: xcode10
xcode_workspace: Crust.xcworkspace
xcode_scheme: Crust
xcode_sdk: iphonesimulator12.0
script:
 - set -o pipefail
 - xcodebuild -version
 - xcodebuild -showsdks
 - xcodebuild -workspace Crust.xcworkspace -scheme Crust -sdk iphonesimulator -destination "OS=12.0,name=iPhone 8" ONLY_ACTIVE_ARCH=NO build test
