language: objective-c
osx_image: xcode10.2
xcode_workspace: Crust.xcworkspace
xcode_scheme: Crust
xcode_sdk: iphonesimulator12.2
script:
 - set -o pipefail
 - xcodebuild -version
 - xcodebuild -showsdks
 - xcodebuild -workspace Crust.xcworkspace -scheme Crust -sdk iphonesimulator -destination "OS=12.2,name=iPhone 8" ONLY_ACTIVE_ARCH=NO build test
