#if !canImport(ObjectiveC)
import XCTest

extension CRMapperTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CRMapperTests = [
        ("testMapFromJSONUsesParentPayload", testMapFromJSONUsesParentPayload),
    ]
}

extension CollectionMappingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CollectionMappingTests = [
        ("testAssigningNullToCollectionWhenAppendNullableDoesNothing", testAssigningNullToCollectionWhenAppendNullableDoesNothing),
        ("testAssigningNullToCollectionWhenNonNullableThrows", testAssigningNullToCollectionWhenNonNullableThrows),
        ("testAssigningNullToCollectionWhenReplaceNullableRemovesAllAndDeletes", testAssigningNullToCollectionWhenReplaceNullableRemovesAllAndDeletes),
        ("testAssigningNullToOptionalCollectionWhenNonNullableThrows", testAssigningNullToOptionalCollectionWhenNonNullableThrows),
        ("testAssigningNullToOptionalCollectionWhenReplaceNullableAssignsNullAndDeletes", testAssigningNullToOptionalCollectionWhenReplaceNullableAssignsNullAndDeletes),
        ("testDefaultInsertionPolicyIsReplaceUniqueNullable", testDefaultInsertionPolicyIsReplaceUniqueNullable),
        ("testMappingArrayOfOptionalEnums", testMappingArrayOfOptionalEnums),
        ("testMappingCollection", testMappingCollection),
        ("testMappingCollectionByAppend", testMappingCollectionByAppend),
        ("testMappingCollectionByReplace", testMappingCollectionByReplace),
        ("testMappingCollectionByReplaceDelete", testMappingCollectionByReplaceDelete),
        ("testMappingEquatableCollectionByReplaceDeleteUnique", testMappingEquatableCollectionByReplaceDeleteUnique),
    ]
}

extension CompanyMappingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CompanyMappingTests = [
        ("testJsonToCompany", testJsonToCompany),
        ("testNestedJsonToCompany", testNestedJsonToCompany),
        ("testNilOptionalNilsRelationship", testNilOptionalNilsRelationship),
        ("testUsesExistingObject", testUsesExistingObject),
    ]
}

extension EmployeeMappingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EmployeeMappingTests = [
        ("testJsonToEmployee", testJsonToEmployee),
    ]
}

extension NestedMappingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NestedMappingTests = [
        ("testMappingBeginCalledWhenNestedMappingOfDifferentAdapter", testMappingBeginCalledWhenNestedMappingOfDifferentAdapter),
        ("testMappingWillBeginCalledOnlyOnceWhenNestedMappingOfSameAdapter", testMappingWillBeginCalledOnlyOnceWhenNestedMappingOfSameAdapter),
    ]
}

extension StructMappingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StructMappingTests = [
        ("testNilClearsOptionalValue", testNilClearsOptionalValue),
        ("testStructMapping", testStructMapping),
    ]
}

extension TransformTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TransformTests = [
        ("testCustomTransformOverridesDefaultOne", testCustomTransformOverridesDefaultOne),
        ("testMappingFromJSON", testMappingFromJSON),
        ("testMappingToJSON", testMappingToJSON),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CRMapperTests.__allTests__CRMapperTests),
        testCase(CollectionMappingTests.__allTests__CollectionMappingTests),
        testCase(CompanyMappingTests.__allTests__CompanyMappingTests),
        testCase(EmployeeMappingTests.__allTests__EmployeeMappingTests),
        testCase(NestedMappingTests.__allTests__NestedMappingTests),
        testCase(StructMappingTests.__allTests__StructMappingTests),
        testCase(TransformTests.__allTests__TransformTests),
    ]
}
#endif
